### ISSUE TITLE
Reihenfolge .mod_article > .inside

### ISSUE THREAD

**Issue by keckmoritz** [nutshell-framework/assets#2]
Hallo,
ich habe eine Verständnisfrage zur Klasse .inside in scss/base/_article.scss.
Der standardmäßige Output von Contao sieht ja irgendwie so aus:
```
<main id="main">
<div class="inside">
<div class="mod_article">
<div class="content-image">
…
```
In scss/base/_article.scss ist die Reihenfolge aber umgekehrt (.mod_article > .inside). Warum ist das so? Vielen Dank für einen Hinweis, wenn ich auf dem Schlauch stehe ;)

**Comment by denniserdmann** [comment]
Moin!

Wir verwenden ein angepasstes mod_article Template, das einen zusätzlichen Inside-Container hat: https://github.com/nutshell-framework/core-bundle/blob/develop/src/Resources/contao/templates/modules/mod_article.html5#L24

Damit lassen sich dann Hintergrundfarben vollflächig zuweisen, während der Inhalt von .inside eine maximale Breite haben kann. Im LASR Theme kannst du sehen was ich meine: https://lasr-4.contao-theme.de/dokumentation/layout/artikel.html

**Comment by tuxenberger** [comment]
Danke für deine Antwort und die beschrieben Lösungsansätze. 

Mein Gedanke dazu: CSS Grid und Flex kommen immer dann zum Einsatz, wenn der "Standard" der Browserdarstellung die gewünschte Ausrichtung/Verteilung von Inhalten nicht hergibt (Ordne Elemente nebeneinander an, verteile Sie...). Es steht immer ein Element unter den Anderen, in der Reihenfolge wie es in Sourcecode steht. Wenn das nicht sein soll fängt man an per zusätzlichem CSS einzugreifen.

Mit der aktuellen Anpassung wird die Änderung aber zur Regel. Ich muss also mehr Aufwand (und CSS) vom Browser verarbeiten und berechnen lassen um wieder auf den Normalfall zurückzukommen (Reset -> Anpassung in nutshell -> Anpassung in Theme). Alternativ fände ich es besser wenn die Anpassung als Option mit einer CSS-Klasse aktiviert wird.

Am Ende bist Du der Entwickler des Frameworks und entscheidest wo es sich hin entwickeln wird. Ich schätze deine Arbeit sehr und hoffe das du meine Gedanken nicht als unberechtigte Kritik auffasst.

**Comment by denniserdmann** [comment]
@tuxenberger Ich verstehe deine Anmerkung nicht. Bist du sicher, dass sich diese auf dieses Ticket bezieht? Die Frage und meine Antwort haben nichts mit Grid und Flexbox zu tun.

**Comment by tuxenberger** [comment]
Sorry für die Konfusion, war im falschen Ticket gepostet :-(
